[project]
name = "file-assistant"
created = "2025-11-01T16:48:27.250849"
framework_version = "0.3.5"

[cli]
version = "1.0.0"
command = "co create file-assistant"
template = "minimal"

[agent]
address = "0x72b59cf6e9c6fd2eceb6bfaa1e482468f66ab1b4f886518da96d62ec299039ad"
short_address = "0x72b5...39ad"
email = "0x72b59cf6@mail.openonion.ai"
email_active = false
created_at = "2025-11-01T16:48:27.250858"
algorithm = "ed25519"
default_model = "gpt-4o-mini"
max_iterations = 10
